### ISSUE TITLE
replacing localhost with IP address

### ISSUE THREAD

**Issue by dbsiegel** [reshamas/fastai_deeplearn_part1#10]
this has been a fantastic resource, thanks. 

I had some trouble with the part  which says: "I need to replace localhost section with my IP address. 
What would have been clearer to me:  "I need to replace localhost section with the public IP address of my paperspace machine"

**Comment by reshamas** [comment]
@d3borah thanks for the suggestion.  I've updated the text so it is clearer.
https://github.com/reshamas/fastai_deeplearn_part1/blob/master/tools/paperspace.md#step-3--get-notebook-url
