### ISSUE TITLE
Jupyter notebook taking too long to respond

### ISSUE THREAD

**Issue by balajib26** [reshamas/fastai_deeplearn_part1#12]
In my case jupyter notebook is taking too long to respond on my local pc. I followed all the steps.

Also, can you tell me how to copy files from my local pc to cloud pc

**Comment by reshamas** [comment]
a)  [paperspace support](https://github.com/reshamas/fastai_deeplearn_part1/blob/master/tools/paperspace.md#paperspace-support)
b)  [scp (secure copy)](https://github.com/reshamas/fastai_deeplearn_part1/blob/master/tools/copy_files_local_to_cloud.md)
