### ISSUE TITLE
Newer version of proc_df throws ValueError in lesson1-rf.ipynb

### ISSUE THREAD

**Issue by Krogsager** [reshamas/fastai_deeplearn_part1#13]
lesson1-rf.ipynb needs to be updated: first cell in the section "Reducing over-fitting" - "Subsampling", proc_df i called.
`df_trn, y_trn = proc_df(df_raw,'SalePrice')`
and throws
`ValueError: too many values to unpack (expected 2)`

proc_df returns 3 variables rather than two. From the documentation:
> [x, y, nas, mapper(optional)]:

So it could be `df_trn, y_trn, foo = proc_df(df_raw,'SalePrice')`

**Comment by reshamas** [comment]
@Krogsager seems like this issue is better assigned to the source repo:
https://github.com/fastai/fastai

**Comment by Krogsager** [comment]
You are right. I will move it.
