### ISSUE TITLE
paperspace now requiring some justification/approval

### ISSUE THREAD

**Issue by navels** [reshamas/fastai_deeplearn_part1#14]
Going through the setup instructions, ran into this:

>This instance type has not been enabled in your account yet. For some GPU types we require that you tell us a bit more about your use case before we enable access. This is designed to reduce fraud and thus keep our prices low.
Tell us a bit more about your use case and we will prioritize your request (required)

I entered "Deep Learning for Coders Course" and clicked submit and an hour later, nothing, no response yet.  I've got $15 credit on my account (using the coupon code) and have also entered my credit card billing information.

Just throwing this out there as maybe this isn't the best option for the course, or perhaps you want to note this experience on the README.

Other than that, thanks for the great setup instructions!

**Comment by navels** [comment]
FYI my approval took about four hours.

**Comment by reshamas** [comment]
thanks @navels .
