### ISSUE TITLE
Dont seem to be able to attach a template

### ISSUE THREAD

**Issue by eckhardtpasenau** [reshamas/fastai_deeplearn_part1#16]
Did paperspace change the template process? I cannot assign the fastai template during the creation of the machine. Later it does provide the option to assign a template, but I still cannot access public templates.

I am on a windows machine and the European Server. I have asked paperspace support.

**Comment by reshamas** [comment]
@eckhardtpasenau 
- Only the P5000 machines are available at the moment.  
- Requests take about 4-5 hours to be processed.

If it's taking any longer, you may want to go with the AWS option.
