### ISSUE TITLE
Possible inaccuracy in `grep` when listing the number of files.

### ISSUE THREAD

**Issue by ghost** [reshamas/fastai_deeplearn_part1#18]
The following command will incorrectly count the number of files (will overestimate by one), because the first line of output of `ls -l` on some versions of Linux as well as Mac OS X will give the total number of files:
```bash
!ls -l {PATH}train/cats | grep ^[^d] | wc -l
```

I suggest correcting it to the following version which will disregard the first line of `ls -l`:
```bash
!ls -l {PATH}train/cats | grep ^[^dt] | wc -l
```

**Comment by reshamas** [comment]
thanks @fazzolini 
revised the grep syntax in [tips_faq_beginners.md](https://github.com/reshamas/fastai_deeplearn_part1/blob/master/tips_faq_beginners.md)
