### ISSUE TITLE
P4000 available now

### ISSUE THREAD

**Issue by benuklove** [reshamas/fastai_deeplearn_part1#20]
I just got a P4000 on paperspace so [this](https://github.com/reshamas/fastai_deeplearn_part1/blob/master/tools/paperspace.md#step-5--choose-machine) might not be true anymore.

**Comment by reshamas** [comment]
thanks @benuklove 
changed text to:
- Machines to choose (whichever you prefer and is available in your region of choice)
  - the **P4000** `$0.40/hr` (cheapest one) 
  - the **P5000** `$0.65/hr`
