### ISSUE TITLE
can I setup fastai learning env in my Centos7.1  with cuda8.0

### ISSUE THREAD

**Issue by li10141110** [reshamas/fastai_deeplearn_part1#21]
can I setup fastai learning env in my Centos7.1  with cuda8.0, I don't want to change my cuda8.0 to cuda90~~

**Comment by reshamas** [comment]
@li10141110 
that's a good question to ask on the forums.  Here's one possible thread:
http://forums.fast.ai/t/cuda-error-45-no-kernel-image-pytorch-0-3-1-post2/14063

**Comment by li10141110** [comment]
Thank you, reshamas!
