### ISSUE TITLE
facing this problem in paperspace machine

### ISSUE THREAD

**Issue by saiamrit** [reshamas/fastai_deeplearn_part1#25]
the error message that is coming up is thid after doing $conda update env .How to solve this
CondaVerificationError: The package for pytorch located at /home/paperspace/anaconda3/pkgs/pytorch-0.3.1-py36_cuda9.0.176_cudnn7.0.5_2
appears to be corrupted. The path 'lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so'
specified in the package manifest cannot be found.

**Comment by KristianMSchmidt** [comment]
I have the same problem

**Comment by reshamas** [comment]
Please post this on the forum:  http://forums.fast.ai
(I have not been through PyTorch for this documentation.)
