### ISSUE TITLE
Text under 'Optional Steps' regarding Jupyter Notebook not visible.

### ISSUE THREAD

**Issue by ritajit** [reshamas/fastai_deeplearn_part1#26]

**Comment by reshamas** [comment]
Can you send the link to the page?

**Comment by ritajit** [comment]
Sure,

https://github.com/reshamas/fastai_deeplearn_part1/blob/master/tools/paperspace.md

**Comment by reshamas** [comment]
This is what I see. Is it not the same for you?  What browser are you using?

<img width="897" alt="screen shot 2018-06-01 at 7 41 21 am" src="https://user-images.githubusercontent.com/2507232/40839159-429b3b78-656f-11e8-9345-db1e34693a82.png">

**Comment by reshamas** [comment]
Maybe this is what you meant:
"I was looking at the [paperspace setup file](https://github.com/reshamas/fastai_deeplearn_part1/blob/master/tools/paperspace.md#step-6-start-jupyter-notebook--after-logging-into-paperspace-computer-via-ssh-from-your-local-computer) and cannot read the text in Step 6 of Optional Steps at the end."  
Is this what you mean?  I would try some different browsers.

**Comment by ritajit** [comment]
Ah, I see. My mistake, I was confused by the heading sizes under Optional Steps. I didn't realise that "Setup: Simplifying Logging in to Paperspace " was a subheading under "Skip Password and Updating IP Address...". 
It was all a misunderstanding, apologies.
