### ISSUE TITLE
Instructions out of date

### ISSUE THREAD

**Issue by jayurbain** [reshamas/fastai_deeplearn_part1#29]
Your instructions are a little out of date. Selecting the fast.ai template requires prior approval.
Regards,
Jay

**Comment by ceceshao1** [comment]
A similar issue to @jayurbain - the instructions for setting up the machines (templates?) seem out of date. I'm not quite sure how to proceed with setting up the environment - I seem to be getting the email approvals from paperspace but these emails do not contain passwords that I can use to set up in Terminal?

**Comment by wonderjimmy** [comment]
I got the following error after running the command "conda env update"

```
distributed 1.20.2 requires msgpack-python, which is not installed.
spacy 2.0.12 has requirement regex==2017.4.5, but you'll have regex 2017.11.9 which is incompatible.
jupyter-console 5.2.0 has requirement prompt-toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 2.0.5 which is incompatible.
```
It makes the setup of Jupyter Notebook failed. 

I followed the guide and pick P4000, how can I fix that?

**Comment by mischaherbrand** [comment]
I'm running into the same problem.

@ceceshao1 If you chose the US location and the smallest machine, you can setup your account without approval.

**Comment by reshamas** [comment]
A couple of folks have submitted pull requests with some updated instructions.  Can you try again?
