### ISSUE TITLE
Promo code is expired

### ISSUE THREAD

**Issue by monocongo** [reshamas/fastai_deeplearn_part1#34]
The promo code FASTAI6GKZ is no longer valid.

**Comment by seanczak** [comment]
The same happened for me.  It turns out that if you use a referral code, it gives you $10 (not quite $15 but it's something at least).  If you don't figure it out, feel free to use the promo code they gave me for your first $10: PJJ7WWG

Good luck -Sean

**Comment by reshamas** [comment]
@monocongo @seanczak 
promo code has been temporarily extended.  should work now.
