### ISSUE TITLE
cannot use fast.ai under public template

### ISSUE THREAD

**Issue by yrzhou0120berk** [reshamas/fastai_deeplearn_part1#35]
When I try to access the fast.ai template under public section, it asked me for more information before giving me access. 
I put donw ` for fast ai study ` and it has been couple days now but I have not yet heard back from Paperspace, is there anything I should put specifically?

Thanks

**Comment by tsolakoua** [comment]
Same issue here, will write an update if they get back to me. 

Update: @yrzhou0120berk received approval from their side today. Hope the same for you too.

**Comment by CathyZhou0120** [comment]
Yes I have got approval, thank you!
