### ISSUE TITLE
Lesson 1 notebook warning: This notebook will only work with fastai-0.7.x.

### ISSUE THREAD

**Issue by nareshbhatia** [reshamas/fastai_deeplearn_part1#43]
Hi, I followed the directions in README exactly, however when I opened lesson1.ipynb, I got the following warning:

> Important: This notebook will only work with fastai-0.7.x. Do not try to run any fastai-1.x code from this path in the repository because it will load fastai-0.7.x

As a newbie, I don't know which fastai version got installed on my machine. Digging around the forums, it seems that version 1 gets installed by default. So I am not sure how to proceed at this point.

Any help would be greatly appreciated.

Since this is the primary setup link referenced in [lesson 1](https://course.fast.ai/lessons/lesson1.html), it would be really important to keep it accurate and simple for beginners.

**Comment by reshamas** [comment]
Please look under "server setup" in this link: https://course.fast.ai
These are the notebooks to use for version 1.x:  
https://github.com/fastai/course-v3/tree/master/nbs/dl1

**Comment by nareshbhatia** [comment]
Thanks @reshamas, will follow your links.
