### ISSUE TITLE
API key is exposed

### ISSUE THREAD

**Issue by toiletbowlkuku** [reshamas/fastai_deeplearn_part1#47]
@reshamas your api key is exposed 

https://github.com/reshamas/fastai_deeplearn_part1/blob/0edc535dd369651a671fdd297e0346f757b0dafe/courses/v3-dl1/kaggle_fruits.md?plain=1#L6

**Comment by reshamas** [comment]
Thank you @toiletbowlkuku 
Token has been deleted.
